version: '3'
services:
  homeassistant:
    container_name: home-assistant
    hostname: ha-docker
    image: homeassistant/home-assistant:latest
    depends_on:
      - mariadb
      - node-red
    volumes:
      - ${PROJECTS}\Docker-Persistence\home-assistant-docker\config:/config
    environment:
      - TZ=Europe/Madrid
    restart: always
    ports:
      - 8123:8123

  node-red:
    container_name: "node-red"
    environment:
      TZ: TZ=Europe/Madrid
    image: "nodered/node-red"
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ${PROJECTS}\Docker-Persistence\node-red\data:/data

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb-server
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "xxx"
    volumes:
      - ${PROJECTS}\Docker-Persistence\mariadb:/var/lib/mysql