version: '3'
services:
  homeassistant:
    container_name: home-assistant
    hostname: ha-docker
    image: homeassistant/home-assistant:stable
    volumes:
      - ${PROJECTS}\Docker-Persistence\home-assistant-docker\config:/config
    environment:
      - TZ=Europe/Madrid
    restart: always
    ports:
      - 8123:8123

  node-red:
    container_name: "node-red"
    environment:
      TZ: TZ=Europe/Madrid
    image: "nodered/node-red"
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ${PROJECTS}\Docker-Persistence\node-red\data:/data