version: '3'
services:
  homeassistant:
    container_name: home-assistant
    hostname: ha-docker
    image: homeassistant/home-assistant:2021.4.6
    volumes:
      - ${PROJECTS}\Docker-Persistence\home-assistant-docker\config:/config
    environment:
      - TZ=Europe/Madrid
    restart: always
    ports:
      - 8123:8123

  node-red:
    container_name: "node-red"
    environment:
      TZ: TZ=Europe/Madrid
    image: "nodered/node-red"
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ${PROJECTS}\Docker-Persistence\node-red\data:/data

  mysql:
    container_name: mysql
    hostname: mysql-server
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ${PROJECTS}\Docker-Persistence\mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DHA_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DHA_MYSQL_PASSWORD}
      - MYSQL_USER=${DHA_MYSQL_USER}
      - MYSQL_DATABASE=${DHA_MYSQL_DATABASE}